name: tapconnect
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.5.3

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  mobile_scanner: ^6.0.3
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets :
    - .env
